apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: manojmahanta25/auth
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
         - APP_NAME:'authentication'
         - PORT_NUMBER:'3000'
      sync:
        '**/.*ts': .
        '**/*.js': .
        '**/*.json': .

deploy:
  kubectl:
    manifests:
      - k8s/
